name: CMake Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
          - os: ubuntu-20.04
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

      - name: Build with CMake
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Deploy (Linux)
        if: runner.os == 'Linux'
        run: |
          chmod +x ${{ github.workspace }}/build/SnakeQT
          sudo apt-get install fuse libfuse2
          wget -q https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage ${{ github.workspace }}/build/SnakeQT -verbose=2
        shell: bash

      - name: Deploy (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo wget -O /tmp/cqtdeployer.deb https://github.com/QuasarApp/CQtDeployer/releases/download/v1.6.2351/CQtDeployer_1.6.2351.ec4840f_Linux_x86_64.deb
          sudo dpkg -i /tmp/cqtdeployer.deb
          cqtdeployer -bin ${{ github.workspace }}/build/SnakeQT qif
        shell: bash

      - name: Deploy (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cqtdeployer
          cqtdeployer -bin ${{ github.workspace }}/build/SnakeQT qif
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: DistributionKit/*